CBD_CACHE_DIR := cbd_cache/

pcache-y := main.o cache_dev.o backing_dev.o segment.o meta_segment.o logic_dev.o cache.o cache_segment.o key.o req.o writeback.o gc.o \

obj-$(CONFIG_BLK_DEV_PCACHE) += pcache.o

