pcache-y := main.o cache_dev.o backing_dev.o segment.o meta_segment.o logic_dev.o cache.o cache_segment.o cache_key.o cache_req.o cache_writeback.o cache_gc.o

obj-$(CONFIG_BLK_DEV_PCACHE) += pcache.o

